### PR TITLE
Use TextFormat in test_addressbook.R

### PR DESCRIPTION
**Pull request by tanx16**
This resolves https://github.com/eddelbuettel/rprotobuf/issues/98.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Lovely, only two spots.  Easy.  To we have to version protect for older PB releases?

Also, would you mind adding your to file [ChangeLog](https://github.com/eddelbuettel/rprotobuf/blob/master/ChangeLog). Standard GNU / Emacs format of YYYY-MM-DD date, spaces, Name, spaces, email then entries after TAB * filename: description.

**Comment by tanx16** [comment]
Done. 

> Do we have to version protect for older PB releases?

I'm not sure I understand. Are you concerned about using RProtoBuf with older versions of C++ Protobuf? `toTextFormat()` should be fully compatible with any C++ Protobuf version, as it's a stable API. C++ DebugString (and implicitly `as.character` and `toString()`) will eventually have a breaking change, but we don't have a set date for open source yet. When that happens, this change should allow RProtoBuf to update to the latest C++ version, but will likely break RProtoBuf users that happen to use `as.character` or `toString()` for serializing.

**Comment by eddelbuettel** [comment]
Yeah that was my question -- it was nice how we managed to move along from alonger pb2 to newer pb3.  In practice, I suppose, most people will use current versions.  And if `toTextFormat()` was always present it is less of an issue.  Seems we were just sloppy when the test was written.

So big thanks for cleaning that up, and thanks also for obliging with the `ChangeLog` entry.

**Comment by tanx16** [comment]
Happy to help. One alternative to breaking compatibility is to migrate the implementation of those APIs to depend on TextFormat, and instead create a new API that is explicitly a debug format.

**Pull request merged**
