### PR TITLE
clarified license to be GPL (>= 2)

### PR DESCRIPTION
**Pull request by eddelbuettel**
as opposed to GPL 2 as in DESCRIPTION
cf the header files which had this all along

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Any seconds on this?

**Comment by eddelbuettel** [comment]
I'll merge this now.

**Comment by murraystokely** [comment]
Would be more of a fan of moving it away from gpl or dual licensing or
something with Apache, BSD or MIT style license.

Murray

**Comment by eddelbuettel** [comment]
That would be more of a license change which you'd get buy-in from everybody for.  

Here I just clarified in `DESCRIPTION` what the code headers had all this time.  

Personally speaking GPL-2+ is just fine.  I use other licenses on occassion but prefer this one.

**Comment by jeroenooms** [comment]
I'm prefer liberal licenses, so I would approve of `MIT` at least for my share of the code.

**Pull request merged**
