### PR TITLE
Don't crash the deserializer if object has an invalid class set

### PR DESCRIPTION
**Pull request by jefshe**
Relates to https://github.com/eddelbuettel/rprotobuf/issues/28

### CODE REVIEW

**Comment by eddelbuettel** [comment]
The PR fails on the unit tests, and that is a no-no.

**Comment by jefshe** [comment]
fixed now, made a few too many assumptions about the class attribute

**Comment by jefshe** [comment]
@eddelbuettel, could I get your thoughts on the new PR? I just added a catch condition to handle this specific case.

**Comment by eddelbuettel** [comment]
Truly sorry, caught that then ten days ago and was side-tracked, and it got overlooked.  

Will take another look.

**Comment by eddelbuettel** [comment]
Looks fine to me.  Anybody else want to comment?

**Pull request merged**
